---
app_container_name: project-devops-deploy
app_image: "{{ docker_username }}/{{ docker_image }}:latest"
app_port: "8080"
app_management_port: "9090"
app_profile: dev
app_java_opts: "-Xms256m -Xmx512m"
app_healthcheck_url: "http://127.0.0.1:{{ app_management_port }}/actuator/health/readiness"
app_healthcheck_retries: 30
app_healthcheck_delay: 5
