---
app_profile: prod
app_database_port: "5432"
app_database_name: bulletins
app_database_username: bulletins_app
app_database_password: "{{ vault_postgresql_password }}"

app_s3_bucket: "{{ object_storage_bucket }}"
app_s3_region: "{{ object_storage_region }}"
app_s3_access_key: "{{ object_storage_access_key }}"
app_s3_secret_key: "{{ object_storage_secret_key }}"

app_external_services_environment:
  SPRING_DATASOURCE_URL: "{{ app_database_url }}"
  SPRING_DATASOURCE_USERNAME: "{{ app_database_username }}"
  SPRING_DATASOURCE_PASSWORD: "{{ app_database_password }}"
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  STORAGE_S3_BUCKET: "{{ app_s3_bucket }}"
  STORAGE_S3_REGION: "{{ app_s3_region }}"
  STORAGE_S3_ENDPOINT: "{{ app_s3_endpoint }}"
  STORAGE_S3_ACCESSKEY: "{{ app_s3_access_key }}"
  STORAGE_S3_SECRETKEY: "{{ app_s3_secret_key }}"
  STORAGE_S3_CDNURL: "{{ app_s3_cdn_url }}"
