---
database_migration_image: flyway/flyway:12.11.0
database_migration_container_name: project-devops-deploy-migration
database_migration_dir: /var/lib/project-devops-deploy/migrations

database_migration_host: "{{ app_database_host }}"
database_migration_port: "{{ app_database_port }}"
database_migration_name: "{{ app_database_name }}"
database_migration_url: >-
  jdbc:postgresql://{{ database_migration_host }}:{{ database_migration_port }}/{{ database_migration_name }}
database_migration_user: "{{ app_database_username }}"
database_migration_password: "{{ app_database_password }}"

database_migration_baseline_version: "1"
database_migration_connect_retries: "10"
