---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Remove default Nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: app_nginx_remove_default_site | bool

- name: Remove old Nginx conf.d application proxy
  ansible.builtin.file:
    path: /etc/nginx/conf.d/project-devops-deploy.conf
    state: absent

- name: Configure Nginx main configuration
  ansible.builtin.copy:
    src: nginx.conf
    dest: "{{ app_nginx_main_conf_path }}"
    owner: root
    group: root
    mode: "0644"

